library(data.table)
library(reticulate)
library(googlesheets4)
source_python("gibberish_detector.py")
#addresses <- fread("addresses.csv")
gs4_auth(email = "viraljansari@zeptonow.com")
addresses <- read_sheet(ss = "1yU878drtrR3iv3FVLEY46Z07UpDXUcyG7nz7B-uiL54",sheet = "Sheet3")
addresses$result <- mapply(is_gibberish,addresses$addresses)
write_sheet(addresses,ss = "1yU878drtrR3iv3FVLEY46Z07UpDXUcyG7nz7B-uiL54",sheet = "Sheet3")
